services:

  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: gon
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - postgres

  mailhog:
    image: 'mailhog/mailhog:latest'
    container_name: mailhog
    restart: unless-stopped
    ports:
      - '1025:1025' # SMTP Server
      - '8025:8025' # Web UI

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
