version: '3.9'

services:

  postgres:
    image: postgres:alpine
    container_name: postgres_container
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

  mailhog:
    image: 'mailhog/mailhog:latest'
    container_name: mailhog_container
    restart: unless-stopped
    ports:
      - '1025:1025' # SMTP Server
      - '8025:8025' # Web UI

volumes:
  postgres:
