name: 🐛 Bug
description: Report a bug in the project
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: checkboxes
    id: search
    attributes:
      label: Is there an issue for this?
      description: Please search in the issues tab to verify if there is already an issue for the bug you are reporting.
      options:
        - label: I have searched in the existing issues.
          required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the problem you are experiencing
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Provide the environment where you discovered the problem
      multiple: true
      options:
        - Development
        - Production
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Copy and paste any relevant log.
      render: shell
    validations:
      required: false

  - type: textarea
    id: other
    attributes:
      label: Additional context
      placeholder: Provide any additional context about the problem you are experiencing. If possible, include screenshots.
    validations:
      required: false

  - type: dropdown
    id: contribution
    attributes:
      label: Do you want to work on this?
      options:
        - Yes 🚀
        - No 🦥
    validations:
      required: true

