name: 📦 Feature
description: Request a new feature in the project
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: checkboxes
    id: search
    attributes:
      label: Is there an issue for this?
      description: Please search in the issues tab to verify if there is already an issue for the bug you are reporting.
      options:
        - label: I have searched in the existing issues.
          required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the feature you would like to see added
    validations:
      required: true

  - type: dropdown
    id: contribution
    attributes:
      label: Do you want to work on this?
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true

