package main

import (
	"log"
	"os"
)

const comment = `/*
	IMPORTANT NOTICE:
	This file was autogenerated by the task 'db:docs'.
	Run 'task db:docs' to update, not direct edits.
*/

`

func main() {
	filePath := os.Args[1]

	currentContent, err := os.ReadFile(filePath)
	if err != nil {
		log.Fatal(err)
	}

	newContent := append([]byte(comment), currentContent...)
	if err = os.WriteFile(filePath, newContent, os.ModePerm); err != nil {
		log.Fatal(err)
	}
}
