// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

type Todo struct {
	ID          int64  `db:"id" json:"id"`
	Title       string `db:"title" json:"title"`
	IsCompleted bool   `db:"is_completed" json:"is_completed"`
}
